"""Service to generate a high-level summary of arbitrary report data."""

from __future__ import annotations

import asyncio
import json
import logging
from typing import Any

from ..llm import build_client
from ..schemas import ReportSummaryRequest, ReportSummaryResponse

log = logging.getLogger("chroma-ai.report_summary")
_client = build_client()

_LLM_TIMEOUT = 30

SYSTEM_PROMPT = """You are Chroma AI, the elite, highly intelligent system at the core of this modern SaaS platform.
You are reviewing a specific data report generated by the system. The report data is provided as JSON.

Your task is to analyze this data and produce a BEAUTIFUL, PROFESSIONAL INSIGHT REPORT in markdown. 
Make the text outstanding, premium, and very easy to understand. Use a sleek, modern tone.

Structure your analysis elegantly into markdown sections:
- Start with an executive summary.
- Highlight key trends, risks, or anomalies found in the data.
- Provide actionable recommendations.

RULES:
- Be clear, accessible, and beautifully written. Avoid overly dense jargon.
- Reference actual numbers, components, materials, or metrics from the data provided.
- Calculate real percentages if useful. Don't guess.
- Output MUST be a highly professional raw markdown string. Do NOT wrap it in JSON. Do NOT wrap it in a code block. Just return the markdown text directly.
"""

async def summarise(req: ReportSummaryRequest) -> ReportSummaryResponse:
    if not req.payload:
        return ReportSummaryResponse(summary_markdown="No data provided to analyze.")

    user_payload = json.dumps(req.payload)

    for attempt in (1, 2):
        try:
            md = await asyncio.wait_for(
                _client.complete_text(SYSTEM_PROMPT, user_payload),
                timeout=_LLM_TIMEOUT,
            )
            md = md.strip()
            if md:
                return ReportSummaryResponse(summary_markdown=md)
        except asyncio.TimeoutError:
            log.warning(f"Timeout on attempt {attempt}")
        except Exception as e:
            log.error(f"Error on attempt {attempt}: {e}")

    log.error("All report summary attempts failed.")
    return ReportSummaryResponse(
        summary_markdown="⚠️ The AI service is currently overloaded. Please try generating insights again in a few moments.",
        is_fallback=True
    )
